name: Run Python File with User Input

on:
  workflow_dispatch:
    inputs:
      num1:
        description: 'Enter the first number'
        required: true
        default: '0'
      num2:
        description: 'Enter the second number'
        required: true
        default: '0'

jobs:
  run-python-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python script with inputs
        run: |
          echo "Running Python script with user inputs..."
          python sum.py ${{ github.event.inputs.num1 }} ${{ github.event.inputs.num2 }}
